config/routes.rb
Rails.application.routes.draw do
  resources :lines do
    get :search, :on => :collection
  end

  resources :handlers, :only => [:index]

  root 'lines#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line.rb
class Line < ApplicationRecord
  def self.search(term)
    where('LOWER(code) LIKE :term OR LOWER(itinerary) LIKE :term', term: "%#{term.downcase}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  def index
    @lines = Line.order(:code).limit(50)
  end


  def search
    respond_to do |format|
      format.html
      format.json { @lines = Line.search(params[:term]) }
    end
  end

  def show
  end

  def new
    @line = Line.new
  end

  def edit
  end

  def create
    @line = Line.new(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render :show, status: :created, location: @line }
      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url, notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
      @key = '+AIzaSyAGJEmtpjtyx-V5NL4EUpANsydcD2TdYmY'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:code, :itinerary, :company, :terminal, :map_id, :kml_filename)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_class
    "page-#{controller_name} #{action_name.gsub(/-/, '_')}"
  end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/layouts/_footer.html.erb
<footer class="mkd-page-footer" style="padding-top:150px">
  <div class="mkd-footer-bottom-holder">
    <div class="mkd-footer-bottom-inner mkd-grid">
      <div class="mkd-grid-row ">
        <div class="mkd-grid-col-6">

          <div class="widget mkd-image-widget ">
            <a itemprop="url" href="http://lister.mikado-themes.com/" target="_self">
              <%= image_tag('logo-footer-new.png', size: '130x39', alt: 'logo') %>
            </a>
          </div>
        </div>
        <div class="mkd-grid-col-6">
          <div id="nav_menu-2" class="widget mkd-footer-bottom-column-2 widget_nav_menu">
            <div class="menu-footer-menu-container">
              <ul id="menu-footer-menu" class="menu">
                <li id="menu-item-1880" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home menu-item-1880">
                  <a href="http://www.google.com/">Home</a>
                </li>
                <li id="menu-item-1881" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1881">
                  <a href="http://www.google.com/">Sobre</a>
                </li>
                <li id="menu-item-4305" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4305">
                  <a href="http://www.google.com/">Descubra</a>
                </li>
                <li id="menu-item-4306" class="menu-item menu-item-type-taxonomy menu-item-object-job_listing_region menu-item-4306">
                  <a href="http://www.google.com/">Destinos</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Desktop Header -->
<header class="mkd-page-header" style="margin-bottom: 0px;">
  <div class="mkd-fixed-wrapper">
    <div class="mkd-menu-area">
      <div class="mkd-vertical-align-containers">
        <div class="mkd-position-left">
          <div class="mkd-position-left-inner">
            <div class="mkd-logo-wrapper">
              <a itemprop="url" href="/" style="height: 39px;">
                <%= image_tag('lister-logo.png', class: 'mkd-normal-logo', size: '260x78', alt: 'logo') %>
                <%= image_tag('lister-logo.png', class: 'mkd-dark-logo', size: '260x78', alt: 'dark') %>
                <%= image_tag('lister-logo.png', class: 'mkd-light-logo', size: '260x78', alt: 'light') %>
              </a>
            </div>
          </div>
        </div>
        <div class="mkd-position-right">
          <div class="mkd-position-right-inner">
            <div class="widget mkd-button-widget">
              <a itemprop="url" href="/" target="_self" style="color: rgb(255, 255, 255); background-color: rgb(63, 133, 206);"
                 class="mkd-btn mkd-btn-small mkd-btn-solid mkd-btn-custom-hover-bg mkd-btn-custom-hover-color mkd-btn-icon mkd-btn-icon-hover-animation"
                 data-hover-color="#fff" data-hover-bg-color="#4097F6" data-icon-bck-color="#5093D3" data-icon-bck-hover-color="#4FA2F9">
                <span class="mkd-btn-text">Itinerários</span>
                <span class="mkd-btn-icon-html" style="background-color: rgb(80, 147, 211);">
												<span aria-hidden="true" class="fa fa-map-signs"></span>
												<span class="mkd-btn-icon-hover">
													<span aria-hidden="true" class="mkd-icon-font-elegant icon_plus "></span>
												</span>
											</span>
              </a>
            </div>
            <div class="widget mkd-button-widget">
              <a itemprop="url" href="http://www.google.com/" target="_self" style="color: rgb(255, 255, 255); background-color: rgb(63, 133, 206);"
                 class="mkd-btn mkd-btn-small mkd-btn-solid mkd-btn-custom-hover-bg mkd-btn-custom-hover-color mkd-btn-icon mkd-btn-icon-hover-animation"
                 data-hover-color="#fff" data-hover-bg-color="#4097F6" data-icon-bck-color="#5093D3" data-icon-bck-hover-color="#4FA2F9">
                <span class="mkd-btn-text">Logradouros</span>
                <span class="mkd-btn-icon-html" style="background-color: rgb(80, 147, 211);">
												<span aria-hidden="true" class="fa fa-road"></span>
												<span class="mkd-btn-icon-hover">
													<span aria-hidden="true" class="mkd-icon-font-elegant icon_plus "></span>
												</span>
											</span>
              </a>
            </div>
            <div class="widget mkd-login-register-widget"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Mobile Header -->
<header class="mkd-mobile-header" style="margin-bottom: 0px;">
  <div class="mkd-mobile-header-inner">
    <div class="mkd-mobile-header-holder">
      <div class="mkd-grid">
        <div class="mkd-vertical-align-containers">
          <div class="mkd-vertical-align-containers">
            <div class="mkd-position-center">
              <div class="mkd-position-center-inner">
                <div class="mkd-mobile-logo-wrapper">
                  <a itemprop="url" href="http://lister.mikado-themes.com/" style="height: 39px">
                    <%= image_tag('lister-logo.png', size: '260x78', alt: 'Mobile Logo') %>
                  </a>
                </div>
              </div>
            </div>
            <div class="mkd-position-right">
              <div class="mkd-position-right-inner"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_technologies.html.erb
<div class="vc_row wpb_row vc_row-fluid vc_custom_1494499800109 vc_row-has-fill" style="padding-top:80px">
  <div class="wpb_column vc_column_container vc_col-sm-12">
    <div class="vc_column-inner ">
      <div class="wpb_wrapper">
        <div class="mkd-row-grid-section">
          <div class="vc_row wpb_row vc_inner vc_row-fluid">
            <div class="wpb_column vc_column_container vc_col-sm-12">
              <div class="vc_column-inner ">
                <div class="wpb_wrapper">
                  <div class="mkd-clients-carousel-holder  mkd-cc-hover-switch-images">
                    <div class="mkd-cc-inner mkd-owl-slider owl-loaded owl-drag" data-number-of-items="5" data-enable-loop="yes" data-enable-autoplay="yes" data-slider-speed="5000" data-slider-speed-animation="600" data-enable-navigation="no" data-enable-pagination="no" style="visibility: visible;">


                      <div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-1200px, 0px, 0px); transition: 0s; width: 4080px;"><div class="owl-item cloned" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-3.png" alt="a">
                        </a>
                      </div></div><div class="owl-item cloned" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-4.png" alt="a">
                        </a>
                      </div></div><div class="owl-item cloned" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-5.png" alt="a">
                        </a>
                      </div></div><div class="owl-item cloned" style="width: 240px;"><div class="owl-nav disabled">
                        <div class="owl-stage-outer">
                          <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                            <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-2.png" alt="a">
                          </a>
                        </div>
                      </div></div><div class="owl-item cloned" style="width: 240px;"><div class="owl-dots disabled"></div></div><div class="owl-item active" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                          <%= image_tag('h1-tech-1.jpg', class:'mkd-cc-image', alt: 'a') %>
                          <!--<img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-1.png" alt="a">-->
                        </a>
                      </div></div><div class="owl-item active" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-1.png" alt="a">
                        </a>
                      </div></div><div class="owl-item active" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-3.png" alt="a">
                        </a>
                      </div></div><div class="owl-item active" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-4.png" alt="a">
                        </a>
                      </div></div><div class="owl-item active" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-5.png" alt="a">
                        </a>
                      </div></div><div class="owl-item" style="width: 240px;"><div class="owl-nav disabled">
                        <div class="owl-stage-outer">
                          <a itemprop="url" class="mkd-cc-link" href="http://www.google.com" target="_self">
                            <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-2.png" alt="a">
                          </a>
                        </div>

                      </div></div><div class="owl-item" style="width: 240px;"><div class="owl-dots disabled"></div></div><div class="owl-item cloned" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://lister.mikado-themes.com/elements/testimonials/" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-1.png" alt="a">
                        </a>
                      </div></div><div class="owl-item cloned" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://lister.mikado-themes.com/elements/testimonials/" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-2.png" alt="a">
                        </a>
                      </div></div><div class="owl-item cloned" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://lister.mikado-themes.com/elements/testimonials/" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-3.png" alt="a">
                        </a>
                      </div></div><div class="owl-item cloned" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://lister.mikado-themes.com/elements/testimonials/" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-4.png" alt="a">
                        </a>
                      </div></div><div class="owl-item cloned" style="width: 240px;"><div class="owl-stage-outer">
                        <a itemprop="url" class="mkd-cc-link" href="http://lister.mikado-themes.com/elements/testimonials/" target="_self">
                          <img itemprop="image" class="mkd-cc-image" src="http://lister.mikado-themes.com/wp-content/uploads/2017/03/h1-client-5.png" alt="a">
                        </a>
                      </div></div></div></div><div class="owl-nav disabled"><div class="owl-prev"><span class="mkd-prev-icon"><span class="mkd-icon-arrow icon-arrows-left"></span></span></div><div class="owl-next"><span class="mkd-next-icon"><span class="mkd-icon-arrow icon-arrows-right"></span></span></div></div><div class="owl-dots disabled"></div></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buzz</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag    'listing.min', 'listing-responsive.min', 'membership-style.min', 'style', 'modules.min',
                               'modules-responsive.min', 'js_composer.min', 'css', 'main'  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'partials/header' if page_class == 'page-lines search'  %>
    <%= render 'partials/searcher' if page_class == 'page-lines search' %>
    <!--%= render 'layouts/technologies' if page_class == 'page-lines search' %>-->
    <!--%= render 'layouts/footer' if page_class == 'page-lines search' %>-->
    <%= yield %>

  <script>
      $(function() {
          <%= yield :script %>
      });
  </script>

  </body>
</html>

app/views/lines/_form.html.erb
<%= form_with(model: line, local: true) do |form| %>
  <% if line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :line_code %>
  </div>

  <div class="field">
    <%= form.label :itinerary %>
    <%= form.text_field :itinerary, id: :line_itinerary %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :line_company %>
  </div>

  <div class="field">
    <%= form.label :terminal %>
    <%= form.text_field :terminal, id: :line_terminal %>
  </div>

  <div class="field">
    <%= form.label :map_id %>
    <%= form.text_field :map_id, id: :line_map_id %>
  </div>

  <div class="field">
    <%= form.label :kml_filename %>
    <%= form.text_field :kml_filename, id: :line_kml_filename %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>Editing Line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lines</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Itinerary</th>
      <th>Company</th>
      <th>Terminal</th>
      <!--<th>Map</th>-->
      <!--<th>Kml filename</th>-->
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.code %></td>
        <td><%= line.itinerary %></td>
        <td><%= line.company %></td>
        <td><%= line.terminal %></td>
        <!--<td>%= line.map_id %></td>-->
        <!--<td>%= line.kml_filename %></td>-->
        <!--<td>%= link_to 'Show', line %></td>-->
        <!--<td>%= link_to 'Edit', edit_line_path(line) %></td>-->
        <!--<td>%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line', new_line_path %>

app/views/lines/new.html.erb
<h1>New Line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Back', lines_path %>

app/views/lines/search.html.erb
<%= render 'partials/searcher' %>


<!--<article class="app-cont">-->
<!--&lt;!&ndash;<section class="app-title cf">&ndash;&gt;-->
<!--&lt;!&ndash;<h1>Lines</h1>&ndash;&gt;-->
<!--&lt;!&ndash;%= link_to 'New Line', new_line_path %>&ndash;&gt;-->
<!--&lt;!&ndash;</section>&ndash;&gt;-->
<!--<section class="app-content">-->
<!--<div class="books-search">-->
<!--&lt;!&ndash;<input type="text" id="lines-search-txt" autofocus>&ndash;&gt;-->
<!--&lt;!&ndash;<div class="results" id="lines-search-results"></div>&ndash;&gt;-->
<!--</div>-->
<!--</section>-->
<!--</article>-->

app/views/lines/show.html.erb
<style>
  #map {
    height: 660px;
    width: 1100px;
    overflow: hidden;
    float: left;
    border: thin solid #333;
  }
</style>

<div class="mkd-ls-single-header">
  <div class="mkd-ls-single-section-holder top">
    <div class="mkd-ls-single-section mkd-grid clearfix">
      <div class="mkd-ls-single-section-inner  left">
        <div class="mkd-ls-single-part-holder right">

          <div class="mkd-ls-single-part-inner top">
            <div class="mkd-ls-item-title">
              <h3 class="mkd-ls-item-title-inner"><%= @line.code %> | <%= @line.itinerary %></h3>
            </div>
          </div>

          <div class="mkd-ls-single-part-inner bottom">
            <div itemprop="dateCreated" class="mkd-ls-header-info date  entry-date published updated">
              <a itemprop="url" href="http://lister.mikado-themes.com/2017/03/">
                <i class="fa fa-bus" aria-hidden="true"></i> <%= @line.company %></a>
            </div>

              <div class="mkd-listing-rating-holder">
                <div class="mkd-average-rating">
                  <span><i class="fa fa-building-o" aria-hidden="true"></i> <%= @line.terminal %> | <%= @line.kml_filename %></span>
              </div>
              <div class="mkd-listing-rating-stars-holder">
                <span class="mkd-rating-stars" style="width: 71.4%"></span>
              </div>
            </div>

          </div>
        </div>

      </div>

      <div class="mkd-ls-single-section-inner  right">
        <a href="https://www.google.com/maps/d/viewer?hl=pt-BR&mid=1sQLaxVGgxeS3r3EgzT05vkLAsBEaGlLW&ll=-22.908343767465553%2C-43.17516999999998&z=18" target="_blank">
          <button type="submit" style="background-color: #2c84cc;font-size: 14px" class="mkd-btn mkd-btn-huge mkd-btn-solid mkd-btn-fullwidth mkd-ls-single-contact-listing">    <span class="mkd-btn-text">Visualizar no Maps</span>    </button>
        </a>
    </div>
    </div>

    <% kfile = 'http://projetobuzz.com.br/kml/' + @line.kml_filename + '.kmz' %>

    <div class="mkd-ls-single-section-holder bottom">
      <div class="mkd-ls-single-section mkd-grid clearfix">
        <div class="mkd-ls-single-section-inner left">
          <div id="map"></div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
    var map;
    var src = "http://projetobuzz.com.br/kml/<%=@line.kml_filename%>.kmz";

    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: new google.maps.LatLng(-19.257753, 146.823688),
            zoom: 2,
            mapTypeId: 'roadmap'
        });

        var kmlLayer = new google.maps.KmlLayer(src, {
            suppressInfoWindows: true,
            preserveViewport: false,
            map: map
        });
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=<%=@key%>&callback=initMap&region=BR">
</script>

app/views/partials/_copyright.html.erb
<div class="copyright">
  <p>2018 &copy Buzz All rights reserved | Template by  <a href="http://w3layouts.com/" target="_blank">  W3layouts </a></p>
</div>

app/views/partials/_header.html.erb
<!-- Desktop Header -->
<header class="mkd-page-header" style="margin-bottom: 0px;">
  <div class="mkd-fixed-wrapper">
    <div class="mkd-menu-area">
      <div class="mkd-vertical-align-containers">
        <div class="mkd-position-left">
          <div class="mkd-position-left-inner">
            <div class="mkd-logo-wrapper">
              <a itemprop="url" href="/app/assets/stylesheets" style="height: 39px;">
                <%= image_tag('lister-logo.png', class: 'mkd-normal-logo', size: '260x78', alt: 'logo') %>
                <%= image_tag('lister-logo.png', class: 'mkd-dark-logo', size: '260x78', alt: 'dark') %>
                <%= image_tag('lister-logo.png', class: 'mkd-light-logo', size: '260x78', alt: 'light') %>
              </a>
            </div>
          </div>
        </div>
        <div class="mkd-position-right">
          <div class="mkd-position-right-inner">
            <div class="widget mkd-button-widget">
              <a itemprop="url" href="/app/assets/stylesheets" target="_self" style="color: rgb(255, 255, 255); background-color: rgb(63, 133, 206);"
                 class="mkd-btn mkd-btn-small mkd-btn-solid mkd-btn-custom-hover-bg mkd-btn-custom-hover-color mkd-btn-icon mkd-btn-icon-hover-animation"
                 data-hover-color="#fff" data-hover-bg-color="#4097F6" data-icon-bck-color="#5093D3" data-icon-bck-hover-color="#4FA2F9">
                <span class="mkd-btn-text">Itinerários</span>
                <span class="mkd-btn-icon-html" style="background-color: rgb(80, 147, 211);">
												<span aria-hidden="true" class="fa fa-map-signs"></span>
												<span class="mkd-btn-icon-hover">
													<span aria-hidden="true" class="mkd-icon-font-elegant icon_plus "></span>
												</span>
											</span>
              </a>
            </div>
            <div class="widget mkd-button-widget">
              <a itemprop="url" href="http://www.google.com/" target="_self" style="color: rgb(255, 255, 255); background-color: rgb(63, 133, 206);"
                 class="mkd-btn mkd-btn-small mkd-btn-solid mkd-btn-custom-hover-bg mkd-btn-custom-hover-color mkd-btn-icon mkd-btn-icon-hover-animation"
                 data-hover-color="#fff" data-hover-bg-color="#4097F6" data-icon-bck-color="#5093D3" data-icon-bck-hover-color="#4FA2F9">
                <span class="mkd-btn-text">Logradouros</span>
                <span class="mkd-btn-icon-html" style="background-color: rgb(80, 147, 211);">
												<span aria-hidden="true" class="fa fa-road"></span>
												<span class="mkd-btn-icon-hover">
													<span aria-hidden="true" class="mkd-icon-font-elegant icon_plus "></span>
												</span>
											</span>
              </a>
            </div>
            <div class="widget mkd-login-register-widget"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Mobile Header -->
<header class="mkd-mobile-header" style="margin-bottom: 0px;">
  <div class="mkd-mobile-header-inner">
    <div class="mkd-mobile-header-holder">
      <div class="mkd-grid">
        <div class="mkd-vertical-align-containers">
          <div class="mkd-vertical-align-containers">
            <div class="mkd-position-center">
              <div class="mkd-position-center-inner">
                <div class="mkd-mobile-logo-wrapper">
                  <a itemprop="url" href="http://lister.mikado-themes.com/" style="height: 39px">
                    <%= image_tag('lister-logo.png', size: '260x78', alt: 'Mobile Logo') %>
                  </a>
                </div>
              </div>
            </div>
            <div class="mkd-position-right">
              <div class="mkd-position-right-inner"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/partials/_searcher.html.erb
<div class="search">
  <i> </i>
  <div class="s-bar">
    <form>
      <input type="text" id="lines-search-txt" value="Encontre seu buzz" onfocus="this.value = '';"
             onblur="if (this.value == '') {this.value = 'Encontre seu buzz';}"
             class="mkd-ls-main-search-keyword ui-autocomplete-input">
      <input type="submit"  value="Meu Buzz"/>
    </form>
  </div>
  <p>Popular searches: <a href="#">Modern PSD template,</a> <a href="#"> Portfolio design </a></p>
</div>

<%= content_for :script do %>
    new app.Lines;
<% end %>